name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint code (non-failing)
      run: npm run lint:ci
      continue-on-error: true
    
    - name: Build project
      run: npm run build
    
    - name: Check that build artifacts exist
      run: |
        if [ ! -f "build/jquery.tokeninput.min.js" ]; then
          echo "Build failed: build/jquery.tokeninput.min.js not found"
          exit 1
        fi
        echo "Build successful: jquery.tokeninput.min.js created"
        ls -la build/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-assets
        path: build/
        retention-days: 30