name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install Grunt CLI
      run: npm install -g grunt-cli
    
    - name: Lint code
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Check that build artifacts exist
      run: |
        if [ ! -f "build/jquery.tokeninput.min.js" ]; then
          echo "Build failed: build/jquery.tokeninput.min.js not found"
          exit 1
        fi
        echo "Build successful: jquery.tokeninput.min.js created"
        ls -la build/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: built-assets
        path: build/
        retention-days: 30